// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDeveloper(arg1:string):Promise<main.Developer>;

export function AddGroup(arg1:string):Promise<main.Group>;

export function ClearAllDevelopers():Promise<void>;

export function ClearAllGroups():Promise<void>;

export function DeleteDeveloper(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function GetAllDevelopers():Promise<Array<main.Developer>>;

export function GetAllGroups():Promise<Array<main.Group>>;

export function UpdateGroup(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
