// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDeveloper(arg1) {
  return window['go']['main']['App']['AddDeveloper'](arg1);
}

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function ClearAllDevelopers() {
  return window['go']['main']['App']['ClearAllDevelopers']();
}

export function ClearAllGroups() {
  return window['go']['main']['App']['ClearAllGroups']();
}

export function DeleteDeveloper(arg1) {
  return window['go']['main']['App']['DeleteDeveloper'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function GetAllDevelopers() {
  return window['go']['main']['App']['GetAllDevelopers']();
}

export function GetAllGroups() {
  return window['go']['main']['App']['GetAllGroups']();
}

export function UpdateGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3);
}
